// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refreshupdate.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_tokens 
SET updated_at=$1, revoked_at=$2 WHERE token=$3
`

type UpdateRefreshTokenParams struct {
	UpdatedAt time.Time
	RevokedAt sql.NullTime
	Token     string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.UpdatedAt, arg.RevokedAt, arg.Token)
	return err
}
